[eks_nodes]
ip-10-0-11-46.us-west-2.compute.internal ansible_user=ec2-user
ip-10-0-12-157.us-west-2.compute.internal ansible_user=ec2-user
ip-10-0-13-137.us-west-2.compute.internal ansible_user=ec2-user

[monitoring]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
