apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
      volume.kubernetes.io/selected-node: ip-10-0-12-157.us-west-2.compute.internal
      volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    creationTimestamp: "2026-06-07T09:40:42Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: elasticsearch-master
      chart: elasticsearch
      release: elasticsearch
    name: elasticsearch-master-elasticsearch-master-0
    namespace: logging
    resourceVersion: "5719964"
    uid: 6ee9a0b0-b74d-4668-8906-82df611f6dce
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: gp2
    volumeMode: Filesystem
    volumeName: pvc-6ee9a0b0-b74d-4668-8906-82df611f6dce
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 30Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
